import Anthropic from 'https://esm.sh/@anthropic-ai/sdk@0.24.3';

const obj = 'object' as const;
export const TOOL_DEFINITIONS: Anthropic.Tool[] = [
  { name: 'web_search', description: 'Search web for real-time travel info, advisories, events, prices, news.', input_schema: { type: obj, properties: { query: { type: 'string' } }, required: ['query'] } },
  { name: 'get_weather', description: 'Get current/forecast weather via Tomorrow.io.', input_schema: { type: obj, properties: { location: { type: 'string', description: 'City, Country' }, date: { type: 'string', description: 'YYYY-MM-DD or today' } }, required: ['location'] } },
  { name: 'get_visa_requirements', description: 'Visa requirements for a passport holder visiting a country.', input_schema: { type: obj, properties: { passport_country: { type: 'string' }, destination_country: { type: 'string' } }, required: ['passport_country', 'destination_country'] } },
  { name: 'get_travel_advisory', description: 'Travel advisory level and details for a country.', input_schema: { type: obj, properties: { country_code: { type: 'string', description: 'ISO alpha-3 (e.g. EGY)' } }, required: ['country_code'] } },
  { name: 'get_exchange_rate', description: 'Current exchange rate between currencies.', input_schema: { type: obj, properties: { from_currency: { type: 'string' }, to_currency: { type: 'string' } }, required: ['from_currency', 'to_currency'] } },
  { name: 'get_flight_status', description: 'Check flight status by number and date.', input_schema: { type: obj, properties: { flight_number: { type: 'string' }, date: { type: 'string' } }, required: ['flight_number', 'date'] } },
  { name: 'search_flights', description: 'Search flights via Amadeus between two airports on a date.', input_schema: { type: obj, properties: { origin: { type: 'string', description: 'IATA code e.g. JFK' }, destination: { type: 'string', description: 'IATA code e.g. CDG' }, date: { type: 'string' }, passengers: { type: 'number' } }, required: ['origin', 'destination', 'date'] } },
  { name: 'search_hotels', description: 'Search hotels via Amadeus in a city.', input_schema: { type: obj, properties: { destination: { type: 'string', description: 'IATA city code e.g. PAR' }, checkin: { type: 'string' }, checkout: { type: 'string' }, guests: { type: 'number' } }, required: ['destination', 'checkin', 'checkout'] } },
  { name: 'search_experiences', description: 'Search tours/activities via Viator.', input_schema: { type: obj, properties: { destination: { type: 'string' }, category: { type: 'string' } }, required: ['destination'] } },
  { name: 'get_destination_intel', description: 'Destination overview via Google Places.', input_schema: { type: obj, properties: { destination: { type: 'string' } }, required: ['destination'] } },
  { name: 'get_map', description: 'Get a static map image URL for a location via Mapbox.', input_schema: { type: obj, properties: { location: { type: 'string', description: 'Place name or lat,lng' }, zoom: { type: 'number', description: '1-18, default 13' }, markers: { type: 'string', description: 'Comma-separated lat,lng pairs for pins' } }, required: ['location'] } },
  { name: 'get_directions', description: 'Driving/walking/cycling directions between two points via Mapbox.', input_schema: { type: obj, properties: { origin: { type: 'string', description: 'lat,lng or place name' }, destination: { type: 'string', description: 'lat,lng or place name' }, mode: { type: 'string', description: 'driving, walking, cycling, driving-traffic' } }, required: ['origin', 'destination'] } },
  { name: 'get_nearby_places', description: 'Find POIs near a location via Google Places.', input_schema: { type: obj, properties: { location: { type: 'string', description: 'Place name or lat,lng' }, type: { type: 'string', description: 'restaurant, hotel, attraction, pharmacy, atm, hospital' }, radius: { type: 'number', description: 'meters, default 1000' } }, required: ['location'] } },
  { name: 'get_distance', description: 'Distance and travel time between two points via Mapbox.', input_schema: { type: obj, properties: { origin: { type: 'string', description: 'lat,lng' }, destination: { type: 'string', description: 'lat,lng' }, mode: { type: 'string', description: 'driving, walking, cycling' } }, required: ['origin', 'destination'] } },
];
