import { supabase } from '@/lib/supabase/client';
import {
  SafetyAlert,
  CheckIn,
  SafetyScore,
} from '@/features/trips/plugins/safety/types/safety.types';

interface CulturalTip {
  id: string;
  countryCode: string;
  city: string | null;
  locationName: string | null;
  category: string;
  isDo: boolean;
  title: string;
  description: string;
  importance: string;
  icon: string | null;
  activeWhen: string | null;
  source: string | null;
  sourceUrl: string | null;
  severity: string | null;
  penalty: string | null;
  isCritical: boolean;
  tags: string[];
  tabLabel: string | null;
}

function mapAlert(row: any): SafetyAlert {
  return {
    id: row.id,
    type: row.type,
    level: row.level,
    title: row.title,
    description: row.description,
    location: row.location ?? undefined,
    affectedAreas: row.affected_areas ?? undefined,
    validUntil: row.effective_until ? new Date(row.effective_until) : undefined,
    source: row.source,
    actionRequired: row.action_required ?? false,
    createdAt: new Date(row.created_at),
    aiGenerated: row.ai_generated ?? false,
    relevanceScore: row.relevance_score ?? undefined,
  };
}

function mapCheckin(row: any): CheckIn {
  return {
    id: row.id,
    timestamp: new Date(row.created_at),
    location: row.location ?? { latitude: 0, longitude: 0 },
    status: row.status,
    message: row.message ?? undefined,
    autoGenerated: row.auto_generated ?? false,
  };
}

function mapCulturalTip(row: any): CulturalTip {
  return {
    id: row.id,
    countryCode: row.country_code,
    city: row.city ?? null,
    locationName: row.location_name ?? null,
    category: row.category,
    isDo: row.is_do,
    title: row.title,
    description: row.description,
    importance: row.importance,
    icon: row.icon ?? null,
    activeWhen: row.active_when ?? null,
    source: row.source ?? null,
    sourceUrl: row.source_url ?? null,
    severity: row.severity ?? null,
    penalty: row.penalty ?? null,
    isCritical: row.is_critical ?? false,
    tags: row.tags ?? [],
    tabLabel: row.tab_label ?? null,
  };
}

interface SafetyProfile {
  id: string;
  tripId: string;
  safetyScore: number;
  safetyLabel: string;
  safetyDisplayLabel: string;
  safetyColor: string;
  scoreComponents: Record<string, number>;
  scoreVerdict: string;
  travelerAdjustments: string[];
  overview: any;
  threatModel: any;
  neighborhoodMap: any;
  healthMedical: any;
  naturalHazards: any;
  digitalSafety: any;
  womensSafety: any;
  lgbtqSafety: any;
  advisoryLevels: any;
  localEvents: any[];
  emergencyContacts: any[];
  beforeYouGo: any[];
  duringTripProtocols: any[];
  survivalPhrases: any[];
  destination: string;
  destinationCountry: string;
  generatedBy: string;
  createdAt: string;
  updatedAt: string;
}

function mapSafetyProfile(row: any): SafetyProfile {
  return {
    id: row.id,
    tripId: row.trip_id,
    safetyScore: row.safety_score ?? 0,
    safetyLabel: row.safety_label ?? 'unknown',
    safetyDisplayLabel: row.safety_display_label ?? '',
    safetyColor: row.safety_color ?? 'gray',
    scoreComponents: row.score_components ?? {},
    scoreVerdict: row.score_verdict ?? '',
    travelerAdjustments: row.traveler_adjustments ?? [],
    overview: row.overview ?? {},
    threatModel: row.threat_model ?? {},
    neighborhoodMap: row.neighborhood_map ?? {},
    healthMedical: row.health_medical ?? {},
    naturalHazards: row.natural_hazards ?? {},
    digitalSafety: row.digital_safety ?? {},
    womensSafety: row.womens_safety ?? {},
    lgbtqSafety: row.lgbtq_safety ?? {},
    advisoryLevels: row.advisory_levels ?? {},
    localEvents: row.local_events ?? [],
    emergencyContacts: row.emergency_contacts ?? [],
    beforeYouGo: row.before_you_go ?? [],
    duringTripProtocols: row.during_trip_protocols ?? [],
    survivalPhrases: row.survival_phrases ?? [],
    destination: row.destination ?? '',
    destinationCountry: row.destination_country ?? '',
    generatedBy: row.generated_by ?? '',
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

class SafetyService {
  async generateSafetyProfile(tripId: string): Promise<{
    success: boolean;
    safetyScore?: number;
    emergencyContacts?: number;
    protocols?: number;
    modelUsed?: string;
    error?: string;
  }> {
    const { data, error } = await supabase.functions.invoke('generate-safety', {
      body: { tripId },
    });
    if (error) throw new Error(`Safety profile generation failed: ${error.message}`);
    if (data?.error) throw new Error(data.error);
    return data;
  }

  async getSafetyProfile(tripId: string): Promise<SafetyProfile | null> {
    const { data, error } = await supabase
      .from('safety_profiles')
      .select('*')
      .eq('trip_id', tripId)
      .maybeSingle();

    if (error) throw new Error(error.message);
    if (!data) return null;
    return mapSafetyProfile(data);
  }

  async generateDosDonts(tripId: string): Promise<{
    success: boolean;
    tipsGenerated?: number;
    error?: string;
  }> {
    const { data, error } = await supabase.functions.invoke('generate-dos-donts', {
      body: { tripId },
    });
    if (error) throw new Error(`Do's & Don'ts generation failed: ${error.message}`);
    if (data?.error) throw new Error(data.error);
    return data;
  }

  async getTripCulturalTips(tripId: string): Promise<CulturalTip[]> {
    const { data, error } = await supabase
      .from('cultural_tips')
      .select('*')
      .eq('trip_id', tripId)
      .eq('ai_generated', true)
      .order('is_critical', { ascending: false })
      .order('importance', { ascending: false });

    if (error) throw new Error(error.message);
    return (data ?? []).map(mapCulturalTip);
  }

  async clearGeneratedTips(tripId: string): Promise<void> {
    await supabase
      .from('cultural_tips')
      .delete()
      .eq('trip_id', tripId)
      .eq('ai_generated', true);
  }

  async getAlerts(tripId: string): Promise<SafetyAlert[]> {
    const { data, error } = await supabase
      .from('safety_alerts')
      .select('*')
      .eq('trip_id', tripId)
      .is('dismissed_at', null)
      .order('created_at', { ascending: false });

    if (error) throw new Error(error.message);
    return (data ?? []).map(mapAlert);
  }

  async dismissAlert(alertId: string): Promise<void> {
    const { error } = await supabase
      .from('safety_alerts')
      .update({ dismissed_at: new Date().toISOString() })
      .eq('id', alertId);

    if (error) throw new Error(error.message);
  }

  async getCheckins(tripId: string): Promise<CheckIn[]> {
    const { data, error } = await supabase
      .from('safety_checkins')
      .select('*')
      .eq('trip_id', tripId)
      .order('created_at', { ascending: false });

    if (error) throw new Error(error.message);
    return (data ?? []).map(mapCheckin);
  }

  async createCheckin(
    tripId: string,
    userId: string,
    input: { status: string; message?: string; location?: any },
  ): Promise<CheckIn> {
    const { data, error } = await supabase
      .from('safety_checkins')
      .insert({
        trip_id: tripId,
        user_id: userId,
        status: input.status,
        message: input.message ?? null,
        location: input.location ?? null,
        auto_generated: false,
      })
      .select()
      .single();

    if (error) throw new Error(error.message);
    return mapCheckin(data);
  }

  async getCulturalTips(countryCode: string, city?: string): Promise<CulturalTip[]> {
    let query = supabase
      .from('cultural_tips')
      .select('*')
      .eq('country_code', countryCode)
      .order('importance', { ascending: false });

    if (city) {
      // Fetch both country-level tips (city IS NULL) and city-specific tips
      query = query.or(`city.eq.${city},city.is.null`);
    }

    const { data, error } = await query;

    if (error) throw new Error(error.message);
    return (data ?? []).map(mapCulturalTip);
  }

  async getSafetyScore(destination: string): Promise<SafetyScore | null> {
    // Compute a score from active alerts for a given destination
    const { data, error } = await supabase
      .from('safety_alerts')
      .select('*')
      .eq('is_active', true)
      .ilike('title', `%${destination}%`);

    if (error) throw new Error(error.message);

    const alerts = data ?? [];
    if (alerts.length === 0) {
      return {
        overall: 85,
        breakdown: {
          crime: 80,
          health: 90,
          political: 85,
          natural: 90,
          infrastructure: 80,
        },
        trend: 'stable',
        lastUpdated: new Date(),
        sources: ['baseline'],
      };
    }

    const levelPenalty: Record<string, number> = {
      danger: 30,
      warning: 20,
      caution: 10,
      safe: 0,
    };

    const typeToBucket: Record<string, keyof SafetyScore['breakdown']> = {
      security: 'crime',
      health: 'health',
      travel_advisory: 'political',
      natural_disaster: 'natural',
      weather: 'natural',
      local_incident: 'crime',
    };

    const breakdown: SafetyScore['breakdown'] = {
      crime: 90,
      health: 90,
      political: 90,
      natural: 90,
      infrastructure: 85,
    };

    for (const alert of alerts) {
      const penalty = levelPenalty[alert.level] ?? 10;
      const bucket = typeToBucket[alert.type] ?? 'crime';
      breakdown[bucket] = Math.max(0, breakdown[bucket] - penalty);
    }

    const overall = Math.round(
      Object.values(breakdown).reduce((s, v) => s + v, 0) / 5,
    );

    return {
      overall,
      breakdown,
      trend: overall >= 70 ? 'stable' : 'declining',
      lastUpdated: new Date(),
      sources: ['safety_alerts'],
    };
  }
}

export const safetyService = new SafetyService();
export default safetyService;
