/**
 * SAFETY PLUGIN - TYPE DEFINITIONS
 * 
 * This plugin provides real-time safety monitoring and emergency assistance.
 * 
 * AI INTEGRATION POINTS:
 * 1. Monitor user's GPS location in real-time during trip
 * 2. Track travel advisories from government sources (State Dept, FCO, etc.)
 * 3. Analyze local news for safety incidents (protests, crime, natural disasters)
 * 4. Generate safety scores based on destination data
 * 5. Send proactive alerts when user enters unsafe areas
 * 6. Suggest safe routes and areas based on time of day
 * 7. Auto-detect emergencies (sudden location changes, SOS triggers)
 */

export enum SafetyLevel {
  SAFE = 'safe',           // Green - Safe to travel
  CAUTION = 'caution',     // Yellow - Exercise caution
  WARNING = 'warning',     // Orange - Reconsider travel
  DANGER = 'danger',       // Red - Do not travel
}

export enum AlertType {
  TRAVEL_ADVISORY = 'travel_advisory',     // Government travel warnings
  WEATHER = 'weather',                     // Severe weather alerts
  HEALTH = 'health',                       // Disease outbreaks, health risks
  SECURITY = 'security',                   // Crime, terrorism, civil unrest
  NATURAL_DISASTER = 'natural_disaster',   // Earthquakes, floods, etc.
  LOCAL_INCIDENT = 'local_incident',       // Nearby incidents detected by AI
}

export enum EmergencyType {
  MEDICAL = 'medical',
  POLICE = 'police',
  FIRE = 'fire',
  EMBASSY = 'embassy',
  ROADSIDE = 'roadside',
}

export interface EmergencyContact {
  type: EmergencyType;
  name: string;
  number: string;
  description: string;
  available24_7: boolean;
}

export interface SafetyAlert {
  id: string;
  type: AlertType;
  level: SafetyLevel;
  title: string;
  description: string;
  location?: string;
  affectedAreas?: string[];
  validUntil?: Date;
  source: string;
  actionRequired: boolean;
  createdAt: Date;
  
  // AI fields
  aiGenerated: boolean;
  relevanceScore?: number;  // AI: How relevant to user's current location/plans
}

export interface SafeZone {
  id: string;
  type: 'hospital' | 'police' | 'embassy' | 'safe_area';
  name: string;
  address: string;
  coordinates: {
    latitude: number;
    longitude: number;
  };
  distance?: number;        // AI: Calculate from user's current location
  phone?: string;
  hours?: string;
  services?: string[];
}

export interface CheckIn {
  id: string;
  timestamp: Date;
  location: {
    latitude: number;
    longitude: number;
    address?: string;
  };
  status: 'safe' | 'need_help' | 'emergency';
  message?: string;
  autoGenerated: boolean;   // AI: Auto check-in vs manual
}

export interface LocationShare {
  id: string;
  contactName: string;
  contactPhone: string;
  contactEmail: string;
  isActive: boolean;
  startedAt: Date;
  expiresAt?: Date;
  shareRealTime: boolean;   // Continuous vs on-demand
}

export interface SafetyScore {
  overall: number;          // 0-100
  breakdown: {
    crime: number;
    health: number;
    political: number;
    natural: number;
    infrastructure: number;
  };
  trend: 'improving' | 'stable' | 'declining';
  lastUpdated: Date;
  sources: string[];
}

export interface BeforeYouGoItem {
  id: string;
  category: 'vaccination' | 'insurance' | 'documentation' | 'registration' | 'preparation';
  title: string;
  description: string;
  required: boolean;
  completed: boolean;
  dueDate?: Date;
  link?: string;
}

/**
 * AI SAFETY MONITORING SYSTEM
 * 
 * REAL-TIME MONITORING:
 * 1. GPS Tracking:
 *    - Track user location every 5 minutes during trip
 *    - Detect if user enters high-risk areas
 *    - Alert if user deviates significantly from planned route
 *    - Detect unusual movement patterns (e.g., rapid location changes)
 * 
 * 2. Geofencing:
 *    - Create virtual boundaries around unsafe areas
 *    - Alert when user approaches or enters these zones
 *    - Suggest alternative routes in real-time
 * 
 * 3. Time-based Safety:
 *    - Different safety scores for day vs night
 *    - Alert if user is in unsafe area after dark
 *    - Suggest safe areas based on time of day
 * 
 * DATA SOURCES:
 * 1. Government Travel Advisories:
 *    - US State Department
 *    - UK Foreign Office
 *    - Canadian Travel Advisory
 *    - Australian DFAT
 * 
 * 2. News & Social Media:
 *    - Monitor local news for incidents
 *    - Track Twitter/X for real-time reports
 *    - Analyze Reddit travel forums
 *    - Parse police reports and crime data
 * 
 * 3. Weather Services:
 *    - National weather services
 *    - Severe weather alerts
 *    - Natural disaster warnings
 * 
 * 4. Health Organizations:
 *    - WHO disease outbreak alerts
 *    - CDC travel health notices
 *    - Local health department updates
 * 
 * PROACTIVE ALERTS:
 * 1. Location-based:
 *    - "You're approaching an area with high crime. Consider alternative route."
 *    - "Protest reported 2 blocks away. Avoid this area."
 *    - "It's getting dark. This area is unsafe at night. Suggest nearby safe zones."
 * 
 * 2. Time-based:
 *    - Morning: "Good morning! Here's today's safety briefing for [city]"
 *    - Evening: "Reminder: Check in with your emergency contacts"
 *    - Night: "You're in [area] at night. Stay alert. Nearest police: 0.3 mi"
 * 
 * 3. Event-based:
 *    - "Breaking: Earthquake detected in your area. Seek shelter immediately."
 *    - "Travel advisory updated: Avoid downtown due to protests."
 *    - "Weather alert: Heavy rain expected. Flooding possible in low areas."
 * 
 * EMERGENCY DETECTION:
 * 1. Automatic triggers:
 *    - SOS button pressed
 *    - Rapid location changes (possible kidnapping)
 *    - No movement for extended period in unsafe area
 *    - User enters extremely high-risk zone
 *    - Shake phone 3 times (secret SOS)
 * 
 * 2. Emergency response:
 *    - Send location to emergency contacts
 *    - Display local emergency numbers
 *    - Provide nearest hospital/police/embassy
 *    - Start recording audio/video (if enabled)
 *    - Send automated messages to contacts
 * 
 * CHECK-IN SYSTEM:
 * 1. Smart reminders:
 *    - AI suggests check-in times based on itinerary
 *    - Remind if no check-in after X hours
 *    - Auto check-in if user is in safe area (with confirmation)
 * 
 * 2. Missed check-in protocol:
 *    - Send reminder notification
 *    - If still no response, alert emergency contacts
 *    - Provide last known location
 *    - Suggest actions for contacts
 * 
 * MACHINE LEARNING:
 * 1. Pattern recognition:
 *    - Learn user's typical movement patterns
 *    - Detect anomalies (unusual routes, times, areas)
 *    - Predict potential risks based on historical data
 * 
 * 2. Personalization:
 *    - Adapt alert frequency to user preferences
 *    - Learn which alerts user finds helpful
 *    - Customize safety recommendations
 * 
 * 3. Predictive safety:
 *    - Predict crime likelihood by area and time
 *    - Forecast safety trends for upcoming days
 *    - Suggest safest times to visit attractions
 * 
 * PRIVACY & SECURITY:
 * - All location data encrypted end-to-end
 * - User controls who sees their location
 * - Option to disable tracking anytime
 * - Data deleted after trip ends (unless saved)
 * - No third-party sharing without consent
 */
