/**
 * DETAIL PAGE ROUTE
 * 
 * Universal detail page for destinations
 * Route: /detail/[id]
 */

import { useLocalSearchParams } from 'expo-router';
import DetailPageTemplate from '@/components/templates/DetailPageTemplate/DetailPageTemplate';

// TODO: Replace with actual API call
const MOCK_DATA = {
  '1': {
    name: 'Paris',
    location: 'France, Europe',
    rating: 4.8,
    category: 'City',
    visitors: '2.5M+ visitors',
    description: 'Paris, the City of Light, is one of the most iconic destinations in the world. Known for its stunning architecture, world-class museums, and romantic atmosphere, Paris offers an unforgettable experience. From the Eiffel Tower to the Louvre, from charming cafés to haute cuisine restaurants, every corner of this magnificent city tells a story. Whether you\'re strolling along the Seine, exploring Montmartre, or enjoying a croissant at a sidewalk café, Paris captivates visitors with its timeless beauty and cultural richness.',
    practicalInfo: [
      { icon: 'clock', label: 'Best Time to Visit', value: 'April - October' },
      { icon: 'price', label: 'Average Daily Budget', value: '$150 - $300' },
      { icon: 'calendar', label: 'Recommended Duration', value: '4-7 days' },
      { icon: 'phone', label: 'Emergency Number', value: '112', actionable: true },
    ],
    reviews: [
      {
        id: '1',
        userName: 'Sarah Johnson',
        userAvatar: 'https://i.pravatar.cc/150?img=1',
        rating: 5,
        date: '2 weeks ago',
        reviewText: 'Paris exceeded all my expectations! The Eiffel Tower at sunset was breathtaking, and the food was incredible. Every corner of this city is Instagram-worthy. Highly recommend visiting in spring!',
        photos: [
          'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400',
          'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=400',
        ],
        helpful: 24,
      },
      {
        id: '2',
        userName: 'Michael Chen',
        userAvatar: 'https://i.pravatar.cc/150?img=12',
        rating: 4,
        date: '1 month ago',
        reviewText: 'Amazing city with so much history and culture. The Louvre alone could take days to explore. Only downside was it can get quite crowded during peak season.',
        helpful: 18,
      },
      {
        id: '3',
        userName: 'Emma Williams',
        userAvatar: 'https://i.pravatar.cc/150?img=5',
        rating: 5,
        date: '2 months ago',
        reviewText: 'Absolutely magical! The architecture, the cafés, the art... Paris is a dream come true. Don\'t miss Montmartre and the Latin Quarter!',
        photos: [
          'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=400',
        ],
        helpful: 31,
      },
    ],
    similarItems: [
      {
        id: '4',
        name: 'London',
        location: 'United Kingdom, Europe',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=400',
        category: 'City',
      },
      {
        id: '5',
        name: 'Rome',
        location: 'Italy, Europe',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=400',
        category: 'City',
      },
      {
        id: '6',
        name: 'Barcelona',
        location: 'Spain, Europe',
        rating: 4.6,
        image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=400',
        category: 'City',
      },
    ],
    images: [
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
      'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800',
      'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800',
      'https://images.unsplash.com/photo-1431274172761-fca41d930114?w=800',
    ],
    places: [
      {
        id: '1',
        name: 'Eiffel Tower',
        description: 'The Eiffel Tower, located in Paris, France, is an iconic iron lattice structure and one of the most recognizable landmarks in the world.',
        image: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=400',
        distance: '0.5 Miles',
        category: 'Attractions',
        latitude: 48.8584,
        longitude: 2.2945,
      },
      {
        id: '2',
        name: 'Louvre Museum',
        description: 'The world\'s largest art museum and a historic monument in Paris, home to thousands of works including the Mona Lisa.',
        image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=400',
        distance: '1.2 Miles',
        category: 'Attractions',
        latitude: 48.8606,
        longitude: 2.3376,
      },
      {
        id: '3',
        name: 'Notre-Dame Cathedral',
        description: 'A medieval Catholic cathedral, considered one of the finest examples of French Gothic architecture.',
        image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400',
        distance: '1.5 Miles',
        category: 'Attractions',
        latitude: 48.8530,
        longitude: 2.3499,
      },
      {
        id: '4',
        name: 'Le Jules Verne',
        description: 'Michelin-starred restaurant located on the Eiffel Tower\'s second floor, offering exquisite French cuisine.',
        image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400',
        distance: '0.5 Miles',
        category: 'Restaurants',
        latitude: 48.8583,
        longitude: 2.2944,
      },
      {
        id: '5',
        name: 'Café de Flore',
        description: 'One of the oldest coffeehouses in Paris, a famous meeting place for intellectuals and artists.',
        image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400',
        distance: '2.1 Miles',
        category: 'Restaurants',
        latitude: 48.8542,
        longitude: 2.3320,
      },
      {
        id: '6',
        name: 'Musée Rodin',
        description: 'A hidden gem museum dedicated to the works of French sculptor Auguste Rodin, set in a beautiful garden.',
        image: 'https://images.unsplash.com/photo-1566127444979-b3d2b654e3a6?w=400',
        distance: '0.8 Miles',
        category: 'Hidden Gems',
        latitude: 48.8553,
        longitude: 2.3159,
      },
      {
        id: '7',
        name: 'Sainte-Chapelle',
        description: 'A royal chapel with stunning stained glass windows, often overlooked by tourists but absolutely breathtaking.',
        image: 'https://images.unsplash.com/photo-1549144511-f099e773c147?w=400',
        distance: '1.8 Miles',
        category: 'Hidden Gems',
        latitude: 48.8554,
        longitude: 2.3450,
      },
    ],
    safetyInfo: [
      {
        id: '1',
        category: 'Pickpocketing',
        title: 'High Pickpocketing Zone',
        detail: 'Central Market and Main Square areas experience frequent pickpocketing incidents, especially during 8 AM - 4 PM. Be extra cautious with bags and wallets in crowded areas during lunchtime and early evening.',
        severity: 'high',
        iconType: 'warning',
      },
      {
        id: '2',
        category: 'Tourist Scams',
        title: 'Common Tourist Scams',
        detail: 'Eiffel Tower and Champs-Élysées areas: Be aware of petition scams, ring scams, and overpriced souvenirs. Always verify prices before purchasing and avoid signing petitions from strangers.',
        severity: 'medium',
        iconType: 'info',
      },
      {
        id: '3',
        category: 'Safe Areas',
        title: 'Well-Patrolled Districts',
        detail: 'Louvre, Notre-Dame, and Latin Quarter have increased police presence and are generally safe for tourists. However, remain vigilant with personal belongings at all times.',
        severity: 'low',
        iconType: 'location',
      },
    ],
    creatorContent: [
      {
        id: '1',
        platform: 'tiktok',
        thumbnail: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=400',
        title: 'Inside the Most Famous Museum "I See Mona lisa..."',
        location: 'Paris',
        distance: '0.92 Miles',
        likes: '12.5k',
        category: 'On Trending',
      },
      {
        id: '2',
        platform: 'tiktok',
        thumbnail: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400',
        title: 'I Really Lost My Word For This, SO SO Elegan',
        location: 'Paris',
        distance: '0.92 Miles',
        likes: '12.8k',
        category: 'On Trending',
      },
      {
        id: '3',
        platform: 'instagram',
        thumbnail: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=400',
        title: 'Paris Night Life is Absolutely Stunning!',
        location: 'Paris',
        distance: '1.2 Miles',
        likes: '8.3k',
        category: 'Night Life',
      },
      {
        id: '4',
        platform: 'instagram',
        thumbnail: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400',
        title: 'Best French Cuisine Experience Ever',
        location: 'Paris',
        distance: '0.5 Miles',
        likes: '15.2k',
        category: 'Restaurant',
      },
      {
        id: '5',
        platform: 'youtube',
        thumbnail: 'https://images.unsplash.com/photo-1431274172761-fca41d930114?w=400',
        title: 'Exploring Hidden Gems of Montmartre',
        location: 'Paris',
        distance: '2.1 Miles',
        likes: '22.1k',
        category: 'Activities',
      },
      {
        id: '6',
        platform: 'youtube',
        thumbnail: 'https://images.unsplash.com/photo-1549144511-f099e773c147?w=400',
        title: 'Seine River Cruise at Sunset',
        location: 'Paris',
        distance: '1.5 Miles',
        likes: '18.7k',
        category: 'Activities',
      },
    ],
    vibes: [
      {
        id: '1',
        name: 'Mountmartre',
        description: 'Mountmarte is famous for its bohemian spirit & artistic heritage, Montmartre is home to the iconic Sacré-Cœur...',
        distance: '0.8 Miles',
        image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400',
        tags: ['Artsy', 'Historic', 'Social'],
      },
      {
        id: '2',
        name: 'Le Cafe De Paris',
        description: 'Whether you\'re sipping a morning espresso or enjoyers, savoring a delicious meal, or simply watching the world go by...',
        distance: '1.2 Miles',
        image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400',
        tags: ['Nature', 'Coffee'],
      },
      {
        id: '3',
        name: 'Luxembourg Gardens',
        description: 'A beautiful public park perfect for a romantic stroll, picnic, or simply relaxing by the fountains.',
        distance: '1.5 Miles',
        image: 'https://images.unsplash.com/photo-1524396309943-e03f5249f002?w=400',
        tags: ['Nature', 'Romantic'],
      },
      {
        id: '4',
        name: 'Latin Quarter',
        description: 'Historic neighborhood filled with bookshops, cafés, and vibrant student life around the Sorbonne.',
        distance: '0.9 Miles',
        image: 'https://images.unsplash.com/photo-1431274172761-fca41d930114?w=400',
        tags: ['Historic', 'Foodie', 'Nightlife'],
      },
    ],
    localEvents: [
      {
        id: '1',
        title: 'Sunrise Yoga Session at the Floor of Eiffel Tower',
        location: '1st Floor of the Eiffel Tower',
        date: 'Dec 12, 2024',
        time: '8:00 PM - 10:00 PM',
        description: 'Start your day with a peaceful sunrise yoga session on the green lawns of Champ de Mars, with the stunning Eiffel Tower as your backdrop.',
        image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
      },
      {
        id: '2',
        title: 'Louvre Night Tour: Art After Dark',
        location: 'Louvre Museum, Main Hall',
        date: 'Dec 13, 2024',
        time: '7:00 PM - 10:00 PM',
        description: 'Experience the Louvre like never before with an exclusive after-hours tour. See the Mona Lisa and other masterpieces without the daytime crowds.',
        image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=400',
      },
      {
        id: '3',
        title: 'Seine River Jazz Cruise',
        location: 'Port de la Bourdonnais',
        date: 'Dec 14, 2024',
        time: '8:30 PM - 11:30 PM',
        description: 'Enjoy live jazz music while cruising along the Seine River. See Paris\'s illuminated monuments including Notre-Dame and the Eiffel Tower.',
        image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400',
      },
    ],
  },
  '2': {
    name: 'Tokyo',
    location: 'Japan, Asia',
    rating: 4.9,
    category: 'City',
    visitors: '3.2M+ visitors',
    description: 'Tokyo is a vibrant metropolis where ancient traditions blend seamlessly with cutting-edge technology. Experience the serenity of historic temples, the energy of bustling shopping districts, and the precision of Japanese cuisine. From the iconic Shibuya Crossing to peaceful gardens, from anime culture to sumo wrestling, Tokyo offers endless discoveries for every traveler.',
    practicalInfo: [
      { icon: 'clock', label: 'Best Time to Visit', value: 'March - May, Sept - Nov' },
      { icon: 'price', label: 'Average Daily Budget', value: '$120 - $250' },
      { icon: 'calendar', label: 'Recommended Duration', value: '5-7 days' },
      { icon: 'phone', label: 'Emergency Number', value: '110', actionable: true },
    ],
    reviews: [
      {
        id: '1',
        userName: 'David Kim',
        userAvatar: 'https://i.pravatar.cc/150?img=8',
        rating: 5,
        date: '1 week ago',
        reviewText: 'Tokyo is mind-blowing! The perfect blend of tradition and innovation. The food scene is unmatched, and the people are incredibly polite and helpful.',
        helpful: 42,
      },
      {
        id: '2',
        userName: 'Lisa Anderson',
        userAvatar: 'https://i.pravatar.cc/150?img=9',
        rating: 5,
        date: '3 weeks ago',
        reviewText: 'Best city I\'ve ever visited! From temples to tech, Tokyo has it all. The public transportation is amazing and makes getting around so easy.',
        photos: ['https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400'],
        helpful: 28,
      },
    ],
    similarItems: [
      {
        id: '7',
        name: 'Seoul',
        location: 'South Korea, Asia',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=400',
        category: 'City',
      },
      {
        id: '8',
        name: 'Singapore',
        location: 'Singapore, Asia',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=400',
        category: 'City',
      },
      {
        id: '9',
        name: 'Bangkok',
        location: 'Thailand, Asia',
        rating: 4.6,
        image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=400',
        category: 'City',
      },
    ],
    images: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
      'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800',
      'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?w=800',
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800',
    ],
  },
  '3': {
    name: 'New York',
    location: 'USA, North America',
    rating: 4.7,
    category: 'City',
    visitors: '4.1M+ visitors',
    description: 'New York City, the city that never sleeps, is a global hub of culture, finance, and entertainment. From the Statue of Liberty to Times Square, from world-class Broadway shows to diverse neighborhoods, NYC pulses with energy 24/7. Experience incredible museums, diverse cuisines from around the world, and the unmistakable New York attitude.',
    practicalInfo: [
      { icon: 'clock', label: 'Best Time to Visit', value: 'April - June, Sept - Nov' },
      { icon: 'price', label: 'Average Daily Budget', value: '$200 - $400' },
      { icon: 'calendar', label: 'Recommended Duration', value: '5-7 days' },
      { icon: 'phone', label: 'Emergency Number', value: '911', actionable: true },
    ],
    reviews: [
      {
        id: '1',
        userName: 'James Rodriguez',
        userAvatar: 'https://i.pravatar.cc/150?img=13',
        rating: 5,
        date: '4 days ago',
        reviewText: 'NYC is electric! There\'s always something happening. Broadway shows were incredible, and the food diversity is unmatched. A must-visit for everyone!',
        photos: ['https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=400'],
        helpful: 35,
      },
      {
        id: '2',
        userName: 'Sophie Martin',
        userAvatar: 'https://i.pravatar.cc/150?img=10',
        rating: 4,
        date: '2 weeks ago',
        reviewText: 'Loved the energy and diversity! So many museums, parks, and neighborhoods to explore. Can be overwhelming but that\'s part of the charm.',
        helpful: 22,
      },
    ],
    similarItems: [
      {
        id: '10',
        name: 'Los Angeles',
        location: 'USA, North America',
        rating: 4.5,
        image: 'https://images.unsplash.com/photo-1534190239940-9ba8944ea261?w=400',
        category: 'City',
      },
      {
        id: '11',
        name: 'Chicago',
        location: 'USA, North America',
        rating: 4.6,
        image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=400',
        category: 'City',
      },
      {
        id: '12',
        name: 'San Francisco',
        location: 'USA, North America',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=400',
        category: 'City',
      },
    ],
    images: [
      'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800',
      'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=800',
      'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=800',
      'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800',
    ],
  },
};

export default function DetailPage() {
  const { id } = useLocalSearchParams();
  
  // Get data based on ID (mock for now)
  const data = MOCK_DATA[id as keyof typeof MOCK_DATA] || MOCK_DATA['1'];

  return (
    <DetailPageTemplate 
      type="destination" 
      id={id as string} 
      data={data}
    />
  );
}
