-- Journey Briefing topic taxonomy seed (spec §5)
insert into journey_topics (key,label,icon,topic_group,is_universal,applies_to,subhub_scope,needs_research,default_for,sort_weight,research_basis) values
('safety_emergency','Safety & Emergencies','shield','Safety & Risk',true,'{}'::text[],'{}'::text[],true,'{}'::text[],60,'Top universal anxiety'),
('scams_crime','Scams & Crime','warning','Safety & Risk',true,'{}'::text[],'{}'::text[],true,'{}'::text[],62,'Universal risk'),
('visa_entry','Visa & Entry','personalcard','Logistics',true,'{}'::text[],'{}'::text[],true,'{}'::text[],64,'Entry requirements vary'),
('laws_regulations','Laws & Regulations','document','Logistics',true,'{}'::text[],'{}'::text[],true,'{}'::text[],66,'Legal context'),
('payments_banking','Payments & Banking','card','Money',true,'{}'::text[],'{}'::text[],false,'{}'::text[],68,'Money handling'),
('prices_budget','Prices & Budget','trending-down','Money',true,'{}'::text[],'{}'::text[],true,'{}'::text[],55,'Cost is #1 driver'),
('getting_around','Getting Around','routing','Logistics',true,'{}'::text[],'{}'::text[],false,'{}'::text[],70,'Local transport'),
('customs_etiquette','Customs & Etiquette','global','Culture',true,'{}'::text[],'{}'::text[],false,'{}'::text[],72,'Cultural norms'),
('health_medication','Health & Medication','health','Health',true,'{}'::text[],'{}'::text[],true,'{}'::text[],65,'Health prep'),
('weather_packing','Weather & Packing','sun','Practical',true,'{}'::text[],'{}'::text[],true,'{}'::text[],74,'Practical prep'),
('food_dining','Food & Dining','activity','Culture',true,'{}'::text[],'{}'::text[],false,'{}'::text[],76,'Dining'),
('whats_happening','What’s Happening','sparkles','Culture',true,'{}'::text[],'{}'::text[],true,'{}'::text[],78,'Events/current'),
('cost_vs_home','Cost vs Home','trending-down','Money',false,array['medical']::text[],'{}'::text[],true,array['medical']::text[],10,'#1 driver'),
('clinic_accreditation','Clinic Accreditation','badge-check','Safety & Risk',false,array['medical','fertility']::text[],'{}'::text[],true,array['medical']::text[],12,'Biggest safety anxiety'),
('the_procedure','The Procedure','stethoscope','Medical',false,array['medical']::text[],'{}'::text[],false,array['medical']::text[],14,'Step by step'),
('recovery_aftercare','Recovery & Aftercare','heartpulse','Medical',false,array['medical','fertility']::text[],'{}'::text[],false,array['medical']::text[],16,'Content gap'),
('whats_in_package','What’s in the Package','badge-check','Medical',false,array['medical']::text[],'{}'::text[],false,'{}'::text[],18,'Bundles'),
('complication_insurance','Complication Insurance','shield','Safety & Risk',false,array['medical']::text[],'{}'::text[],true,'{}'::text[],20,'Cover abroad'),
('choosing_surgeon','Choosing a Surgeon','stethoscope','Medical',false,array['medical']::text[],'{}'::text[],false,'{}'::text[],22,'Surgeon vs tech'),
('red_flags_mills','Red Flags & Mills','warning','Safety & Risk',false,array['medical']::text[],'{}'::text[],false,'{}'::text[],24,'Warning signs'),
('fue_vs_dhi','FUE vs DHI','sparkles','Medical',false,array['medical']::text[],array['hair']::text[],false,'{}'::text[],26,'Hair technique'),
('graft_counts','Graft Counts','sparkles','Medical',false,array['medical']::text[],array['hair']::text[],false,'{}'::text[],28,'Hair grafts'),
('dental_materials_guarantees','Materials & Guarantees','smile','Medical',false,array['medical']::text[],array['dental']::text[],false,'{}'::text[],26,'Dental materials'),
('residency_pathways','Residency Pathways','personalcard','Logistics',false,array['relocation']::text[],'{}'::text[],true,array['relocation']::text[],10,'Visa routes'),
('cost_of_living','Cost of Living','trending-down','Money',false,array['relocation']::text[],'{}'::text[],true,array['relocation']::text[],12,'Monthly costs'),
('housing_rentals','Housing & Rentals','building','Logistics',false,array['relocation']::text[],'{}'::text[],true,array['relocation']::text[],14,'Renting/buying'),
('banking_transfers','Banking & Transfers','card','Money',false,array['relocation']::text[],'{}'::text[],true,'{}'::text[],16,'Accounts'),
('healthcare_access','Healthcare Access','health','Health',false,array['relocation']::text[],'{}'::text[],true,'{}'::text[],18,'Enrolment'),
('schools','Schools','cap','Family',false,array['relocation','worldschool']::text[],'{}'::text[],false,'{}'::text[],20,'Schooling'),
('taxes_residency','Taxes & Residency','document','Money',false,array['relocation']::text[],'{}'::text[],true,'{}'::text[],22,'Tax rules'),
('setting_up','Setting Up','routing','Logistics',false,array['relocation']::text[],'{}'::text[],false,'{}'::text[],24,'Bureaucracy'),
('building_community','Building Community','handshake','Culture',false,array['relocation']::text[],'{}'::text[],false,'{}'::text[],26,'Networks'),
('nomad_visa','Nomad Visa','personalcard','Logistics',false,array['nomad']::text[],'{}'::text[],true,array['nomad']::text[],10,'DN visa'),
('internet_connectivity','Internet & Connectivity','global','Practical',false,array['nomad']::text[],'{}'::text[],true,array['nomad']::text[],12,'Speeds'),
('monthly_budget','Monthly Budget','trending-down','Money',false,array['nomad']::text[],'{}'::text[],true,array['nomad']::text[],14,'Geo-arbitrage'),
('coworking','Coworking','briefcase','Practical',false,array['nomad']::text[],'{}'::text[],true,'{}'::text[],16,'Spaces'),
('best_neighborhoods','Best Neighborhoods','building','Logistics',false,array['nomad']::text[],'{}'::text[],false,'{}'::text[],18,'Where to base'),
('nomad_community','Nomad Community','handshake','Culture',false,array['nomad']::text[],'{}'::text[],false,'{}'::text[],20,'Meetups'),
('timezone_fit','Timezone Fit','clock','Practical',false,array['nomad']::text[],'{}'::text[],false,'{}'::text[],22,'Overlap'),
('nomad_taxes','Nomad Taxes','document','Money',false,array['nomad']::text[],'{}'::text[],true,'{}'::text[],24,'Tax exposure'),
('retreat_types','Retreat Types','sun','Wellness',false,array['wellness']::text[],'{}'::text[],false,array['wellness']::text[],10,'Types'),
('cost_included','Cost & What’s Included','trending-down','Money',false,array['wellness']::text[],'{}'::text[],true,array['wellness']::text[],12,'Pricing'),
('vetting_legitimacy','Vetting & Legitimacy','badge-check','Safety & Risk',false,array['wellness']::text[],'{}'::text[],true,array['wellness']::text[],14,'Avoid scams'),
('best_season','Best Season','sun','Practical',false,array['wellness']::text[],'{}'::text[],true,'{}'::text[],16,'When to go'),
('health_dietary','Health & Dietary','heart','Health',false,array['wellness']::text[],'{}'::text[],false,'{}'::text[],18,'Accommodations'),
('reputation_reviews','Reputation & Reviews','sparkles','Safety & Risk',false,array['wellness']::text[],'{}'::text[],true,'{}'::text[],20,'Reviews'),
('booking_safely','Booking Safely','shield','Safety & Risk',false,array['wellness']::text[],'{}'::text[],false,'{}'::text[],22,'Deposits'),
('col_couple','Cost for a Couple','trending-down','Money',false,array['retire']::text[],'{}'::text[],true,array['retire']::text[],10,'Fixed income'),
('healthcare_quality','Healthcare Quality','health','Health',false,array['retire']::text[],'{}'::text[],true,array['retire']::text[],12,'Quality+access'),
('retiree_visa','Retiree Visa','personalcard','Logistics',false,array['retire']::text[],'{}'::text[],true,array['retire']::text[],14,'Pensionado'),
('climate_comfort','Climate & Comfort','sun','Practical',false,array['retire']::text[],'{}'::text[],true,'{}'::text[],16,'Livability'),
('accessibility','Accessibility','heart','Health',false,array['retire']::text[],'{}'::text[],false,'{}'::text[],18,'Mobility'),
('retiree_community','Retiree Community','handshake','Culture',false,array['retire']::text[],'{}'::text[],false,'{}'::text[],20,'Communities'),
('pensions_banking','Pensions & Banking','card','Money',false,array['retire']::text[],'{}'::text[],true,'{}'::text[],22,'Receiving pension'),
('longterm_safety','Long-term Safety','shield','Safety & Risk',false,array['retire']::text[],'{}'::text[],true,'{}'::text[],24,'Stability'),
('legally_permitted','What’s Legally Permitted','document','Logistics',false,array['fertility']::text[],'{}'::text[],true,array['fertility']::text[],10,'#1 gap'),
('cost_per_cycle','Cost per Cycle','trending-down','Money',false,array['fertility']::text[],'{}'::text[],true,array['fertility']::text[],12,'Package'),
('process_timeline','Process & Timeline','clock','Medical',false,array['fertility']::text[],'{}'::text[],false,array['fertility']::text[],14,'Steps'),
('success_rates_caveated','Success Rates','heartpulse','Medical',false,array['fertility']::text[],'{}'::text[],true,'{}'::text[],16,'Caveated'),
('legal_parentage','Legal Parentage','document','Logistics',false,array['fertility']::text[],'{}'::text[],true,'{}'::text[],18,'Citizenship of child'),
('peer_support','Peer Support','handshake','Culture',false,array['fertility']::text[],'{}'::text[],false,'{}'::text[],20,'Connecting'),
('overall_safety','Overall Safety','shield','Safety & Risk',false,array['solo']::text[],'{}'::text[],true,array['solo']::text[],10,'Realistic picture'),
('cultural_norms_dress','Cultural Norms & Dress','global','Culture',false,array['solo']::text[],'{}'::text[],false,array['solo']::text[],12,'Norms/harassment'),
('safe_neighborhoods','Safe Neighborhoods','building','Safety & Risk',false,array['solo']::text[],'{}'::text[],true,array['solo']::text[],14,'Where to stay'),
('getting_around_safely','Getting Around Safely','routing','Safety & Risk',false,array['solo']::text[],'{}'::text[],false,'{}'::text[],16,'Transport safety'),
('meeting_travelers','Meeting Travelers','handshake','Culture',false,array['solo']::text[],'{}'::text[],false,'{}'::text[],18,'Meeting women'),
('scams_targeting_solo','Scams Targeting Solo','warning','Safety & Risk',false,array['solo']::text[],'{}'::text[],true,'{}'::text[],20,'Common scams'),
('health_wellbeing','Health & Wellbeing','heart','Health',false,array['solo']::text[],'{}'::text[],false,'{}'::text[],22,'Pharmacies')
on conflict (key) do nothing;
