import PreferenceScreen from '@/components/features/onboarding/PreferenceScreen';
import { Global } from 'iconsax-react-native';

export default function CountryScreen() {
  return (
    <PreferenceScreen
      icon={Global}
      title="Where are you from?"
      description="Select your home country"
      inputType="select"
      options={[
        'Algeria',
        'Argentina',
        'Australia',
        'Austria',
        'Bahrain',
        'Bangladesh',
        'Belgium',
        'Brazil',
        'Bulgaria',
        'Cambodia',
        'Cameroon',
        'Canada',
        'Chile',
        'China',
        'Colombia',
        'Costa Rica',
        'Croatia',
        'Cuba',
        'Czech Republic',
        'Denmark',
        'Dominican Republic',
        'Ecuador',
        'Egypt',
        'Estonia',
        'Ethiopia',
        'Finland',
        'France',
        'Germany',
        'Ghana',
        'Guatemala',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Ireland',
        'Israel',
        'Italy',
        'Ivory Coast',
        'Jamaica',
        'Japan',
        'Jordan',
        'Kenya',
        'Kuwait',
        'Laos',
        'Latvia',
        'Lebanon',
        'Libya',
        'Lithuania',
        'Luxembourg',
        'Madagascar',
        'Malaysia',
        'Mauritius',
        'Mexico',
        'Morocco',
        'Myanmar',
        'Nepal',
        'Netherlands',
        'New Zealand',
        'Nigeria',
        'Norway',
        'Oman',
        'Pakistan',
        'Panama',
        'Peru',
        'Philippines',
        'Poland',
        'Portugal',
        'Puerto Rico',
        'Qatar',
        'Romania',
        'Rwanda',
        'Saudi Arabia',
        'Senegal',
        'Serbia',
        'Singapore',
        'Slovakia',
        'Slovenia',
        'South Africa',
        'South Korea',
        'Spain',
        'Sri Lanka',
        'Sweden',
        'Switzerland',
        'Tanzania',
        'Thailand',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkey',
        'Uganda',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom',
        'United States',
        'Venezuela',
        'Vietnam',
      ]}
      currentStep={5}
      totalSteps={10}
      nextRoute="/(onboarding)/language"
      showBackButton={true}
      fieldName="country"
    />
  );
}
